# Generated by Django 5.0.6 on 2024-06-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_listing_time_watch'),
    ]

    operations = [
    ]
