# Generated by Django 5.0.6 on 2024-06-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='has_won',
            field=models.BooleanField(default=False),
        ),
    ]
